### ISSUE TITLE
Wrong redirect 

### ISSUE THREAD

**Issue by pmous** [mcaskill/Slim-Polyglot#10]
Hi,
I tried your middleware, but there seems to be a bug. I do this:
$app->add(
	new Polyglot(
		[
			'languages' => array_keys($container->get('settings')['locales']),
			'fallbackLanguage' => $container->get('settings')['default_language'],
			'languageRequiredInUri' => true,
			'languageIncludedInRoutes' => false,
			'callbacks' => [ ...
I want the language in the url, so languageRequiredInUri is true, but this settings redirects me to /nl/nl. I did some debugging, the problem seems to be on the last part of the __invoke(), on line 374. Here a replace is done, but if getBasePath() is empty, this results in the bad behaviour. So I changed
				$path = str_replace($uri->getBasePath() . '/', '', $response_uri->path);
to:
				$path = $uri->getBasePath() != '' ? str_replace($uri->getBasePath() . '/', '', $response_uri->path) : $response_uri->path;

Now it works. But I am not quite sure if this works correctly if you do have a base path....

Best, Paul

**Comment by pmous** [comment]
@mcaskill I saw you did not yet address my issue. Do you want me to do a pull request? Would be better to stay in sync with your tree for future updates. And I am curious about this base path option. I can't really understand what it is for...

**Comment by mcaskill** [comment]
Hi @pmous, sorry for the long delay. I have merged your changes. Thank you for this.

See [v0.3.3](https://github.com/mcaskill/Slim-Polyglot/releases/tag/v0.3.3).

**Comment by pmous** [comment]
Hi @mcaskill. Of course, no problem! It is fabulous that you maintain this code in the first place!
I see indeed that my change is merged. You put it in another code style: I always try to avoid re-assignments as much as possible, so I work with $responseUri->path and assign $path from that in one go. But again, it is a matter of taste, I guess.
I will try to pull your version later, if It does not work, I'll let you know.

**Comment by mcaskill** [comment]
There's a distinct lack of coding style in the package (and of testing), just continuing that way for now. I hope to clean it up. Maybe even refactor it to be easier to understand and customize.

**Comment by pmous** [comment]
Lol, yes, that is how this often goes. Again, cheers for doing this work! I wish I had more time, then I would love to help you out. But for now, my simple fix is the only thing I can offer...

**Comment by mcaskill** [comment]
The fix is much appreciated. Given the lack of tests in the package, the last pull request resolved a specific edge case but created the one you had.
