### ISSUE TITLE
Info

### ISSUE THREAD

**Issue by kennymuse** [mcaskill/Slim-Polyglot#3]
Hi, how I can import the class?

use McAskill\Slim\Polyglot; don't work

**Comment by mcaskill** [comment]
Hi @kennymuse 

I've updated the [usage examples](https://github.com/mcaskill/Slim-Polyglot/blob/master/README.md#usage) on the README to show the full class namespace for `Polyglot`.

Basically, your use statement is missing a part: `use McAskill\Slim\Polyglot\Polyglot;`

**Comment by kennymuse** [comment]
Ok Thanks. How I can get the value from the request? I can set for example:

Accept-Language : it 

and the library detect it? Or is possible only from the url (in this case work).

**Comment by mcaskill** [comment]
The order of resolution is:
1. Check the Request's URI query parameters (e.g., `/foo?lang=it`)
2. Check the Request's URI path (e.g., `/it/foo`)
3. Check the client's session data  (e.g., `$_SESSION['language']`)
4. Check the Request's "Accept-Language" header (e.g., `Accept-Language: it; q=0.1, en; q=0.4…`)
5. Use the fallback language

Request attributes:
* `language-fallback` — Default language if all else fails
* `language-preferred` — Client's language;
  Value from `$_SESSION` or best choice from `Accept-Language`
* `language-path` — Language used, or to use, in the URI (when redirecting)
* `language-current` — Resolved active language

Response attributes:
* `Content-Language` Header — Resolved active language

Session attributes:
* `$_SESSION['language']` — Resolved active language

**Comment by kennymuse** [comment]
I use 

`$app->add(
	new Polyglot([
		'languages' => ['en', 'it'],
        'fallbackLanguage' => 'en',
		// Hooks to call after language is resolved
		'callbacks' => [
			function ($language) use ($container) {
				$container["language"] = $language;
            }
		]
	])
);`

and in the request I set

Accept-Language: it

but the $language has value "en". I don't understand where I'm wrong

**Comment by mcaskill** [comment]
Nothing appears to be wrong with the setup of the middleware.

Below is a working test page I set up to test the middleware with your settings:

```
<?php

use Slim\App;
use Slim\Http\Environment;
use McAskill\Slim\Polyglot\Polyglot;

require __DIR__ . '/vendor/autoload.php';

session_start();

// Instantiate the app
$app = new App();

// Fetch the service container
$container = $app->getContainer();

// Mock the environment
$container['environment'] = function () {
	return Environment::mock([
		'HTTP_ACCEPT_LANGUAGE' => 'it',
	]);
};

// Register the middleware
$app->add(
	new Polyglot([
		'languages' => [ 'en', 'it' ],
		'fallbackLanguage' => 'en',
		'callbacks' => [
			function ($language) use ($container) {
				$container["language"] = $language;
			}
		]
	])
);

// Register index route
$app->get('/', function ($request, $response) {
	$language = $this['language'];

	echo '<pre>';
	var_dump($language); echo "\n";
	var_dump($_SESSION); echo "\n";
	var_dump($request->getAttributes());
	echo '</pre>';
});

// Run app
$app->run();
```

**Comment by kennymuse** [comment]
I use postman for test http post. I set Accept-Language: it to header and the variable $language is "en". If I execute the request with the param inside the url all work well.

![1](https://user-images.githubusercontent.com/2910774/35375857-d5f9af42-01a8-11e8-9a01-a0c5e4d4c9cf.jpeg)

**Comment by kennymuse** [comment]
I run your code in debug

`    protected function getFromHeader(ServerRequestInterface $request)
    {
        $accept = $request->getHeaderLine('Accept-Language');

        if ( empty($accept) || empty($this->languages) ) {
            return;
        }

        $language = (new Negotiator())->getBest($accept, $this->languages);

        if ( $language ) {
            return $language->getValue();
        }
    }`

At this point, return $language->getValue(); (the value is 'it') to 

`elseif ( ! $this->isSupported($language) ) {
            $language = $this->getUserLanguage($request);
            $request  = $request->withAttribute('language-preferred', $language);

            $language = $fallback;
            $request  = $request->withAttribute('language-path', $language);

            $path       = $this->replaceLanguage($uri->getPath(), $request->getAttribute('language-path'), $language);
            $response   = $response->withRedirect($uri->withPath($path), 303);
            $redirected = true;
        }`

Here I don't understand if '$language = $fallback;' is correct or override the right value 'it' with 'en'

**Comment by kennymuse** [comment]
I understand that in case of request without it inside url, the library treat the case like a fallback but the language-preferred is 'it'.

If I get the value by:

`$lang = $request->getAttribute('language-preferred');`

the value is ok, (it) and $this->language is en.

**Comment by kennymuse** [comment]
the problem is that the library considers 'api' (url http://api.site.com/api/v1.0/login) like a language don't supported but I set Accept-Language to 'it'.

**Comment by kennymuse** [comment]
Possible fix, confirm me if is ok:

`elseif ( ! $this->isSupported($language) ) {
            $language = $this->getUserLanguage($request);
            $request  = $request->withAttribute('language-preferred', $language);

            if ( empty($language) ) {
                $language = $fallback;
            }
            
            $request  = $request->withAttribute('language-path', $language);

            $path       = $this->replaceLanguage($uri->getPath(), $request->getAttribute('language-path'), $language);
            $response   = $response->withRedirect($uri->withPath($path), 303);
            $redirected = true;
        }`

**Comment by mcaskill** [comment]
It's been a while since I've used this middleware and never tested it the way you are using.

I'm seeing a lot of faults in the class now and a lot of overly-complicated routines.

With the fix you've proposed, can you use that in the mean time?

I'd like to sit down soon and refactor this middleware to better support Accept-Language / URI resolution.

I suggest you try out Oscar Otero's [
LanguageNegotiation](https://github.com/oscarotero/psr7-middlewares#languagenegotiation) middleware which only performs a Accept-Language check.

**Comment by kennymuse** [comment]
With the fix proposed I have resolved. For now is ok. I have tested the lang inside the url and inside the Accept-Language. For now is ok. If you fix advise me, thanks. ;-)
